version: "3.7"
services:
  portal:
    container_name: portal
    build: ./portal/.
    restart: always
    ports:
      - 6368:6368
  app:
    container_name: app
    build: ./app/.
    restart: always
