version: "3"
services:
  dbredis:
    build: redis/.
    ports:
      - 6379:6379
    container_name: redis
  dbpostgres:
    build: database/.
    ports:
      - "5432:5432"
    container_name: postgres
