export type FinancialDocument = {
  sigemp: string;
  clienteCod: number;
  representanteCod: number;
  numero: number;
  valor: number;
  dtVencimento: Date;
  ordem: number;
  tipo: string;
  tipoDescricao: string;
  parcela: number;
  sequencia: number;
  numBoleto: number;
  numBoletoDv: number;
  locCob: number;
  fazRemessa: number;
  banco: number;
  agencia: number;
  dtPagamento?: Date;
  dtMovimento?: Date;
  situacao: number;
  dtAlteracao: Date;
};
export type FinancialDocumentFields = {
  sigemp?: boolean;
  clienteCod?: boolean;
  representanteCod?: boolean;
  numero?: boolean;
  valor?: boolean;
  dtVencimento?: boolean;
  ordem?: boolean;
  tipo?: boolean;
  tipoDescricao?: boolean;
  parcela?: boolean;
  sequencia?: boolean;
  numBoleto?: boolean;
  numBoletoDv?: boolean;
  locCob?: boolean;
  fazRemessa?: boolean;
  banco?: boolean;
  agencia?: boolean;
  dtPagamento?: boolean;
  dtMovimento?: boolean;
  situacao?: boolean;
  dtAlteracao?: boolean;
};
